name: multiplayer
description: A game with basic multiplayer support.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  async: ^2.11.0
  audioplayers: ^5.2.0
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.22.0
  go_router: ^12.0.1
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
