name: endless_runner
description: A Flame game template built with Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  flame_audio: ^2.10.2
  go_router: ^14.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  nes_ui: ^0.20.0
  google_fonts: ^6.2.0
  logging: ^1.2.0

dev_dependencies:
  flame_test: ^1.16.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.25.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dash/
    - assets/images/enemies/
    - assets/images/scenery/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
