name: basic
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  go_router: ^17.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
